name: Cleanup Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: terraform8
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform8
        run: |
          terraform destroy -auto-approve \
            -var="aws_region=${AWS_REGION}" \
            -var="image_uri=dummy" \
            -var="execution_role_arn=arn:aws:iam::607700977843:role/ecs-task-execution-role" \
            -var="task_role_arn=arn:aws:iam::607700977843:role/ecs-task-execution-role"

