name: Task 11 - Infra Provisioning

on:
  push:
   branches:
     - santhosh

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: strapi-sk
  IMAGE_TAG: ${{ github.sha }}
  TERRAFORM_DIR: terraform11
  STRAPI_DIR: strapi-app

jobs:
  build-and-deploy:
    name: Build Image and Apply Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin 607700977843.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build, Tag, and Push Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG $STRAPI_DIR
          docker tag $ECR_REPOSITORY:$IMAGE_TAG 607700977843.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          docker push 607700977843.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TERRAFORM_DIR }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.TERRAFORM_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TERRAFORM_DIR }}

