name: Task 7 - Build and Deploy Strapi App

on:
  push:
    branches:
      - santhosh

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: strapi-sk
  IMAGE_TAG: ${{ github.sha }}
  TF_VAR_aws_region: us-east-2
  TF_VAR_execution_role_arn: arn:aws:iam::607700977843:role/ecs-task-execution-role
  TF_VAR_task_role_arn: arn:aws:iam::607700977843:role/ecs-task-execution-role

jobs:
  deploy:
    name: Build, Push to ECR & Deploy to ECS via Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag and Push Docker Image to ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE_URI=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
          docker build -t $IMAGE_URI ./strapi-app
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform7
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform7
        run: terraform plan -out=tfplan 
             -var="image_uri=${{ env.IMAGE_URI }}"

      - name: Terraform Apply
        working-directory: terraform7
        run: terraform apply -auto-approve tfplan

